# Generated by Django 3.2.4 on 2021-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
